export const PollCommands = [
	'camera standby get',
	'camera focus mode get',
	'camera ccu get all',
	'camera led get',
	'video mute get',
]

export const Choices = {
	AutoManual: [
		{ id: 'auto', label: 'Auto' },
		{ id: 'manual', label: 'Manual' },
	],
	CcuScenesR: [
		{ id: 'F1', label: 'Auto' },
		{ id: 'F2', label: 'Incandescent Hi' },
		{ id: 'F3', label: 'Fluorescent Hi' },
		{ id: 'F4', label: 'Outdoor' },
		{ id: 'F5', label: 'Incandescent Lo' },
		{ id: 'F6', label: 'Fluorescent Lo' },
		{ id: 'C1', label: 'Custom A' },
		{ id: 'C2', label: 'Custom B' },
		{ id: 'C3', label: 'Custom C' },
	],
	CcuScenesS: [
		{ id: '1', label: 'Custom A' },
		{ id: '2', label: 'Custom B' },
		{ id: '3', label: 'Custom C' },
	],
	OnOff: [
		{ id: 'on', label: 'On' },
		{ id: 'off', label: 'Off' },
	],
	OnOffToggle: [
		{ id: 'on', label: 'On' },
		{ id: 'off', label: 'Off' },
		{ id: 'toggle', label: 'Toggle' },
	],
}

export const Fields = {
	CcuPresetRecall: {
		type: 'dropdown',
		label: 'Preset',
		id: 'preset',
		default: 'F1',
		choices: Choices.CcuScenesR,
	},
	CcuPresetSave: {
		type: 'dropdown',
		label: 'Preset',
		id: 'preset',
		default: '1',
		choices: Choices.CcuScenesS,
	},
	FocusMode: {
		type: 'dropdown',
		label: 'Focus mode',
		id: 'mode',
		default: 'auto',
		choices: Choices.AutoManual,
	},
	IncludeCcu: {
		type: 'checkbox',
		label: 'Include color data?',
		id: 'ccu',
		default: false,
	},
	OnOff: {
		type: 'dropdown',
		label: 'State',
		id: 'mode',
		default: 'on',
		choices: Choices.OnOff,
	},
	OnOffToggle: {
		type: 'dropdown',
		label: 'State',
		id: 'mode',
		default: 'toggle',
		choices: Choices.OnOffToggle,
	},
	Preset: {
		type: 'number',
		label: 'Preset #',
		id: 'val',
		min: 1,
		max: 16,
		default: 1,
		required: true,
		range: true,
	},
	Speed: function (min, max, def) {
		return {
			type: 'number',
			label: 'Speed',
			id: 'speed',
			min: min,
			max: max,
			default: def,
			required: true,
			range: true,
		}
	},
	Value: function (min, max, def) {
		return {
			type: 'number',
			label: 'Value',
			id: 'value',
			min: min,
			max: max,
			default: def,
			required: true,
			range: true,
		}
	},
}

export const Presets = {
	PanTilt: [
		{
			id: 'up',
			label: 'UP',
			icon: 'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6AQMAAAApyY3OAAABS2lUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDAgNzkuMTYwNDUxLCAyMDE3LzA1LzA2LTAxOjA4OjIxICAgICAgICAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIi8+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+LUNEtwAAAARnQU1BAACxjwv8YQUAAAABc1JHQgCuzhzpAAAABlBMVEUAAAD///+l2Z/dAAAAAXRSTlMAQObYZgAAAIFJREFUKM+90EEKgzAQRmFDFy49ghcp5FquVPBighcRegHBjWDJ68D8U6F7m00+EnhkUlW3ru6rdyCV0INQzSg1zFLLKmU2aeCQQMEEJXIQORRsTLNyKJhNm3IoaPBg4mQorp2Mh1+00kKN307o/bZrpt5O/FlPU/c75X91/fPd6wPRD1eHyHEL4wAAAABJRU5ErkJggg==',
		},
		{
			id: 'down',
			label: 'DOWN',
			icon: 'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6AQMAAAApyY3OAAABS2lUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDAgNzkuMTYwNDUxLCAyMDE3LzA1LzA2LTAxOjA4OjIxICAgICAgICAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIi8+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+LUNEtwAAAARnQU1BAACxjwv8YQUAAAABc1JHQgCuzhzpAAAABlBMVEUAAAD///+l2Z/dAAAAAXRSTlMAQObYZgAAAIlJREFUKM/F0DEOwyAMBVAjDxk5Qo7CtdiClIv1KJF6gUpZIhXxY2zTDJ2benoS8LFN9MsKbYjxF2XRS1UZ4bCeGFztFmNqphURpidm146kpwFvLDYJpPQtLSLNoySyP2bRpoqih2oSFW8K3lYAxmJGXA88XMnjeuDmih7XA8vXvNeeqX6U6aY6AacbWAQNWOPUAAAAAElFTkSuQmCC',
		},
		{
			id: 'left',
			label: 'LEFT',
			icon: 'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6AQMAAAApyY3OAAABS2lUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDAgNzkuMTYwNDUxLCAyMDE3LzA1LzA2LTAxOjA4OjIxICAgICAgICAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIi8+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+LUNEtwAAAARnQU1BAACxjwv8YQUAAAABc1JHQgCuzhzpAAAABlBMVEUAAAD///+l2Z/dAAAAAXRSTlMAQObYZgAAAHpJREFUKM+1kTEOgCAQBM9Q2JjwA/mJPA2fxlN4giWF8TRBBhMpbKSaZie3i8gPb4Y8FNZKGm8YIAONkNWacIruQLejy+gyug1dQhfRqZa0v6gYA6QfqSWapZnto1B6XdUuFaVHoJunr2MD21nIdJYUEhLYfoGmP777BKKIXC0eYSD5AAAAAElFTkSuQmCC',
		},
		{
			id: 'right',
			label: 'RIGHT',
			icon: 'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6AQMAAAApyY3OAAABS2lUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDAgNzkuMTYwNDUxLCAyMDE3LzA1LzA2LTAxOjA4OjIxICAgICAgICAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIi8+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+LUNEtwAAAARnQU1BAACxjwv8YQUAAAABc1JHQgCuzhzpAAAABlBMVEUAAAD///+l2Z/dAAAAAXRSTlMAQObYZgAAAHhJREFUKM+10LERgCAMQFE4CktHcBRWcRMYzVEcwdKCI+od+fGksVCq3/AuiXOfvZnaNXzRClVrEKtMLdSqP2RTRQAFMAFGwAlw7MAk0sAzGnhVoerLKg/F5Pv4NoFNZZNGpk9sxJYeLsDdL5T7S8IFOM/R3OZ+fQeQZV9pMy+bVgAAAABJRU5ErkJggg==',
		},
		{
			id: 'upRight',
			label: 'UP RIGHT',
			icon: 'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6CAMAAAAk2e+/AAABS2lUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDAgNzkuMTYwNDUxLCAyMDE3LzA1LzA2LTAxOjA4OjIxICAgICAgICAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIi8+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+LUNEtwAAAARnQU1BAACxjwv8YQUAAAABc1JHQgCuzhzpAAABhlBMVEUAAAD///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////+X02G5AAAAgXRSTlMAAte32QZhZx7d+TywDTf8/d5VstYPOxULNvKmSY8TFBrxyeGCluJeELQ5uw7ULND4BedlKuv2P/vDA8UgCk30WO41s8+5X8dABAz6QhHVaR156JpPnihSfTJDNOMBm4bzSICqr23NsRjcGRbtjTCS2lzsOmyu9+WLKb2fTL8+RPDhqO4yAAABfElEQVRYw+3WZW/CUBQG4AO0FBsOwwcMm7sLc3d3d3e388/HGGs7lpD0tsm+9P3S5CT3SdPec+8BkCNHzv9FAVAAEABYdQDkA7jo9GNUIDMBzstb5vr0/Gx8Z35zOjI36R2xbu+619eWa2xCoK0FClF5h1cWxDHEwilEOyLlQc8hokoAlMRcESBh7siQlJBWKkijNaHuPrWBED9iYiDQ7Pv1D4Z4/DXyFo2JgeAghQEkEgAvT6IgNo/PIUmgd62oj80mqEIpINoXRkmg2j2UBDIWVXKLTSXEUIOF/xbV5aRQsJvvUOoqMqjZZ+c7FcX8ThYCtTbxHV0fkEGDA73D3Dpzi/6rWEYAdSn579PZ/t3IBJChkef0dLRlHXdkJ6TSmSnmiYPq1LQIiGHX9BvZYinJ7/+R6q1czUG0j9KSOTxDc6UhshZhMIQrS78mncwZtzErrNcYL6V2Zd0tJ6i7QFtAYPcvHv25W6J+/Y3BrRA/x6WGuGN5mpUjhyyfsGtrpKE95HoAAAAASUVORK5CYII=',
		},
		{
			id: 'upLeft',
			label: 'UP LEFT',
			icon: 'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6CAMAAAAk2e+/AAABS2lUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDAgNzkuMTYwNDUxLCAyMDE3LzA1LzA2LTAxOjA4OjIxICAgICAgICAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIi8+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+LUNEtwAAAARnQU1BAACxjwv8YQUAAAABc1JHQgCuzhzpAAABLFBMVEUAAAD///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////9PVkEkAAAAY3RSTlMAAQ/6Uc0OEAvHTzL7TcudsMHvdwnfUwMcG8UGiIfTrIkg9QI+/ZTDe460km73LNovCo1vQUuR4Lwk45/OK+3UERTkekziZlSK8QQnoOsFaaXmLqOylvPZLYDRZTUWUpiTDfAuEmiSAAABUklEQVRYw+3WZ2+DMBAG4EtTygrQ7NHsJt1777333vv+/38o6gIMSo0dqf3AK1lIZ/mRjPEJgCBBgvxtQr8WqDKbCiWUG1AnYXU7C7UJqKQSR5oKQwqIPphsYW24nEPjJCYXilf9F+G+qeTmThTP5w8X8gK9NLqOGMGPhD8fdXtBkGihlmlsmF5aqK2xg9FmQe3/DupuEhTpoT41z/V1HVHfxWRRo/6ORBfyjILx9mRo+2MDlS3ggF5q4uP9qzmVNjfOA+EDdDLcWA8IW6FJEJPkCbFI3hCDZEFVPsmC7mQuyYJ0iUuyIAG4JDvEJTkgHskJcUgExC6RECmxQ4REDa24ILsU6wL/rfYHskmX9C87Pfi9aA5cUmnRx/kffDmncSCkat7X342KSzOIuesNR1WSl7GU8Xfbbs9Gyoo0TvRp6Tie8d2TOsyx51UMEiQIS94B13oTqqYgGGoAAAAASUVORK5CYII=',
		},
		{
			id: 'downRight',
			label: 'DOWN RIGHT',
			icon: 'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6CAMAAAAk2e+/AAABS2lUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDAgNzkuMTYwNDUxLCAyMDE3LzA1LzA2LTAxOjA4OjIxICAgICAgICAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIi8+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+LUNEtwAAAARnQU1BAACxjwv8YQUAAAABc1JHQgCuzhzpAAABXFBMVEUAAAD///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////9jYfXuAAAAc3RSTlMAQ98Ox1j9gAtRNTqBPfgu9p/MTQ+G1Qfx7Y0VBYyJgjkGd3ysU+Zz1IQvMM20PgwBp8Mi4TSUiDvlPxylsaF2WfcjJh0S+wLzQLmY4l/ovX3ra1rPLAOSKa4RUEvgcZwbFHqPzodGbX7qPMvCtsEq1laguT+HEwAAAVlJREFUWMPt1sduwkAQgOGxDfFCIITe0nvvvZHee++992TeX4pJQIC9hPWaQ6T41x6skfY7WGPJAGZm/6qgZjIH4AMgOp2Lq32batTkdW/trPt9+qC70DVmSKS2BXF7A1fX9DDnN2FUSpe8y5hID3SZuJMmrcwmoSFm5vD0BDWSNTnCUmZoD1PZtJCDGfIgRUpBMjPkR4rEAwUtFIkHAkKRuCCaxAdRJE5IK/FCGumWF1JLEW5ILfFD2ST9UBaJA6JLPBCQ57xAJcp5NQbtSgBReJSsH8QI5No8ODo+u397ecL3T35IGhcRA4jig8E9qmjAX2OGnAV5ggrxr0ELOaByVmg6B1TGvEYyTvxcKUaMv/ii7xN/VAZYY2dfSHkkPOYY7Kpf7OmLzLfGPIFGd6izWrRUjdYt9Xfo+ULsLpgRKqGtGyadAEIUmnuhXSAwMAXD5j+omZlZRl+X30CWTm2dHwAAAABJRU5ErkJggg==',
		},
		{
			id: 'downLeft',
			label: 'DOWN LEFT',
			icon: 'iVBORw0KGgoAAAANSUhEUgAAAEgAAAA6CAMAAAAk2e+/AAABS2lUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDAgNzkuMTYwNDUxLCAyMDE3LzA1LzA2LTAxOjA4OjIxICAgICAgICAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIi8+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+LUNEtwAAAARnQU1BAACxjwv8YQUAAAABc1JHQgCuzhzpAAABg1BMVEUAAAD///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8aT76cAAAAgHRSTlMAafwJfflezc+3WA7Z5Rk6PAvpBNE73kJT89QxZ48czNIv9A1DnI3qKQUaymjT4a7HdVuGf85LR20CVHr+tLBlA0GvYSTYZEnbAcazNPX4yB4GrAgnmL6Bcj4qIVKIe8kdVadIEe27B90bOG/3Er1rYJq1wibyh+4Q5CMzRllMXDo5euMAAAGfSURBVFjD7dblUwJBGAbw5aSlBJRGQERBkLC7u7u7u7veP90jDnaEcdhjP+k9X5h9Zu43O7PLe4eQECH/KGsIaUooOEcLK75LpehH628idSrE+nMANfyQ3MY2BRm0C6mM462tUwJAJtVyUB1WmsoSFZEk46D6TBcYS3UKPpCYawxD5VxHImVD/RHIxMQbGintkGQcppkcOkuutQPYfkDfmjck556ZTSydve2YY5UWk0Mww672VPh+XFqCU8tA+whtL+KOpa+bF3Rh8B4ymDNaSnSzG9IPIpsL34/HTPZfS58auMPYuYNMWcQXOsD3U9ZDOkZkkCvqwSIqUI2WfEDmgiQxRANiIp8GKtDLO6/Znw19oOdXhKoROtEUBr1F5Y9f4dt1XygqKgh6YqcHwMQkQBWICr1H6czTgrpoQde0IGnekJEWNEwLMv/GPDDB/M/fDioVeLYA5GqoYt+xNRY4toJkCiBUG7vTEVxJu2Z549RbqXQuba7uVDZWO66mgw6d7kYaEPvvCb+REIp/srGzLP4aa0n8zKFkKUSIkD+Qb9QrYMvxAbaBAAAAAElFTkSuQmCC',
		},
	],
	Presets: [
		{ id: 'recallPset', group: 'Recall Preset', label: 'Recall ', speed: null },
		{ id: 'savePset', group: 'Save Preset (very slow)', label: 'Save ', speed: 1 },
		{ id: 'savePset', group: 'Save Preset (slow)', label: 'Save ', speed: 6 },
		{ id: 'savePset', group: 'Save Preset (medium)', label: 'Save ', speed: 12 },
		{ id: 'savePset', group: 'Save Preset (fast)', label: 'Save ', speed: 18 },
		{ id: 'savePset', group: 'Save Preset (very fast)', label: 'Save ', speed: 24 },
	],
	States: [
		{
			action: 'awbS',
			feedback: 'auto_white_balance',
			group: 'CCU Control',
			label: 'AWB On',
			actionValue: 'on',
			fbValue: 'on',
		},
		{
			action: 'awbS',
			feedback: 'auto_white_balance',
			group: 'CCU Control',
			label: 'AWB Off',
			actionValue: 'off',
			fbValue: 'off',
		},
		{
			action: 'blcS',
			feedback: 'backlight_compensation',
			group: 'CCU Control',
			label: 'Backlight Comp On',
			actionValue: 'on',
			fbValue: 'on',
		},
		{
			action: 'blcS',
			feedback: 'backlight_compensation',
			group: 'CCU Control',
			label: 'Backlight Comp Off',
			actionValue: 'off',
			fbValue: 'off',
		},
		{
			action: 'aIrisS',
			feedback: 'auto_iris',
			group: 'CCU Control',
			label: 'Auto Iris',
			actionValue: 'on',
			fbValue: 'on',
		},
		{
			action: 'aIrisS',
			feedback: 'auto_iris',
			group: 'CCU Control',
			label: 'Manual Iris',
			actionValue: 'off',
			fbValue: 'off',
		},
		{
			action: 'focusM',
			feedback: 'auto_focus',
			group: 'Lens',
			label: 'Auto Focus',
			actionValue: 'auto',
			fbValue: 'on',
		},
		{
			action: 'focusM',
			feedback: 'auto_focus',
			group: 'Lens',
			label: 'Manual Focus',
			actionValue: 'manual',
			fbValue: 'off',
		},
		{
			action: 'wdrS',
			feedback: 'wide_dynamic_range',
			group: 'CCU Control',
			label: 'Wide Dyn Range On',
			actionValue: 'on',
			fbValue: 'on',
		},
		{
			action: 'wdrS',
			feedback: 'wide_dynamic_range',
			group: 'CCU Control',
			label: 'Wide Dyn Range Off',
			actionValue: 'off',
			fbValue: 'off',
		},
		{
			action: 'setStandby',
			feedback: 'standby',
			group: 'Camera Control',
			label: 'Standby On',
			actionValue: 'on',
			fbValue: 'on',
		},
		{
			action: 'setStandby',
			feedback: 'standby',
			group: 'Camera Control',
			label: 'Standby Off',
			actionValue: 'off',
			fbValue: 'off',
		},
		{ action: 'setLed', feedback: 'led', group: 'Camera Control', label: 'LED On', actionValue: 'on', fbValue: 'on' },
		{
			action: 'setLed',
			feedback: 'led',
			group: 'Camera Control',
			label: 'LED Off',
			actionValue: 'off',
			fbValue: 'off',
		},
		{
			action: 'setVidMute',
			feedback: 'mute',
			group: 'Camera Control',
			label: 'Video Mute On',
			actionValue: 'on',
			fbValue: 'on',
		},
		{
			action: 'setVidMute',
			feedback: 'mute',
			group: 'Camera Control',
			label: 'Video Mute Off',
			actionValue: 'off',
			fbValue: 'off',
		},
	],
	Values: [
		{
			action: 'pSpeedU',
			release: null,
			group: 'Pan/Tilt',
			label: 'PAN\\nSPEED\\nUP\\n\\n$(vaddio:pan_speed)',
			size: '7',
		},
		{
			action: 'pSpeedD',
			release: null,
			group: 'Pan/Tilt',
			label: 'PAN\\nSPEED\\nDOWN\\n\\n$(vaddio:pan_speed)',
			size: '7',
		},
		{
			action: 'tSpeedU',
			release: null,
			group: 'Pan/Tilt',
			label: 'TILT\\nSPEED\\nUP\\n\\n$(vaddio:tilt_speed)',
			size: '7',
		},
		{
			action: 'tSpeedD',
			release: null,
			group: 'Pan/Tilt',
			label: 'TILT\\nSPEED\\nDOWN\\n\\n$(vaddio:tilt_speed)',
			size: '7',
		},
		{ action: 'zoomI', release: 'zoomS', group: 'Lens', label: 'ZOOM IN', size: '18' },
		{ action: 'zoomO', release: 'zoomS', group: 'Lens', label: 'ZOOM OUT', size: '18' },
		{
			action: 'zSpeedU',
			release: null,
			group: 'Lens',
			label: 'ZOOM\\nSPEED\\nUP\\n\\n$(vaddio:zoom_speed)',
			size: '7',
		},
		{
			action: 'zSpeedD',
			release: null,
			group: 'Lens',
			label: 'ZOOM\\nSPEED\\nDOWN\\n\\n$(vaddio:zoom_speed)',
			size: '7',
		},
		{ action: 'focusN', release: 'focusS', group: 'Lens', label: 'FOCUS NEAR', size: '18' },
		{ action: 'focusF', release: 'focusS', group: 'Lens', label: 'FOCUS FAR', size: '18' },
		{
			action: 'fSpeedU',
			release: null,
			group: 'Lens',
			label: 'FOCUS\\nSPEED\\nUP\\n\\n$(vaddio:focus_speed)',
			size: '7',
		},
		{
			action: 'fSpeedD',
			release: null,
			group: 'Lens',
			label: 'FOCUS\\nSPEED\\nDOWN\\n\\n$(vaddio:focus_speed)',
			size: '7',
		},
		{ action: 'gainU', release: null, group: 'CCU Control', label: 'GAIN\\nUP\\n\\n$(vaddio:gain)', size: '7' },
		{ action: 'gainD', release: null, group: 'CCU Control', label: 'GAIN\\nDOWN\\n\\n$(vaddio:gain)', size: '7' },
		{
			action: 'rGainU',
			release: null,
			group: 'CCU Control',
			label: 'RED\\nGAIN\\nUP\\n\\n$(vaddio:red_gain)',
			size: '7',
		},
		{
			action: 'rGainD',
			release: null,
			group: 'CCU Control',
			label: 'RED\\nGAIN\\nDOWN\\n\\n$(vaddio:red_gain)',
			size: '7',
		},
		{
			action: 'bGainU',
			release: null,
			group: 'CCU Control',
			label: 'BLUE\\nGAIN\\nUP\\n\\n$(vaddio:blue_gain)',
			size: '7',
		},
		{
			action: 'bGainD',
			release: null,
			group: 'CCU Control',
			label: 'BLUE\\nGAIN\\nDOWN\\n\\n$(vaddio:blue_gain)',
			size: '7',
		},
		{ action: 'irisU', release: null, group: 'CCU Control', label: 'IRIS\\nUP\\n\\n$(vaddio:iris)', size: '7' },
		{ action: 'irisD', release: null, group: 'CCU Control', label: 'IRIS\\nDOWN\\n\\n$(vaddio:iris)', size: '7' },
		{ action: 'detailU', release: null, group: 'CCU Control', label: 'DETAIL\\nUP\\n\\n$(vaddio:detail)', size: '7' },
		{
			action: 'detailD',
			release: null,
			group: 'CCU Control',
			label: 'DETAIL\\nDOWN\\n\\n$(vaddio:detail)',
			size: '7',
		},
		{ action: 'chromaU', release: null, group: 'CCU Control', label: 'CHROMA\\nUP\\n\\n$(vaddio:chroma)', size: '7' },
		{
			action: 'chromaD',
			release: null,
			group: 'CCU Control',
			label: 'CHROMA\\nDOWN\\n\\n$(vaddio:chroma)',
			size: '7',
		},
		{ action: 'gammaU', release: null, group: 'CCU Control', label: 'GAMMA\\nUP\\n\\n$(vaddio:gamma)', size: '7' },
		{ action: 'gammaD', release: null, group: 'CCU Control', label: 'GAMMA\\nDOWN\\n\\n$(vaddio:gamma)', size: '7' },
	],
}
